[programs.localnet]
learn_anchor_1 = "G4a37Uh2bxak2teBAox3zbjQWT2Nr6xgD9jkj7Sgpm16"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/"

[workspace]
types = "app/src/idl/"
